import json
import os
import platform
import re
import shutil
import subprocess
import sys
from datetime import datetime, timedelta, time as dt_time
from pathlib import Path

_CNW: dict = (
    {"creationflags": subprocess.CREATE_NO_WINDOW}
    if platform.system() == "Windows" else {}
)

def _base_dir() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).parent
    return Path(__file__).resolve().parent.parent


def _get_os() -> str:
    _sys = platform.system()
    if _sys == "Darwin":
        return "mac"
    if _sys == "Linux":
        return "linux"
    return "windows"


def _scripts_dir() -> Path:
    d = Path.home() / ".jarvis" / "reminders"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _sanitise(text: str, max_len: int = 200) -> str:
    return (
        text.replace("\\", "")
            .replace('"', "")
            .replace("'", "")
            .replace("\n", " ")
            .replace("\r", "")
            .strip()
    )[:max_len]

def _write_notify_script(task_name: str, message: str, os_name: str) -> Path:
    script_path = _scripts_dir() / f"{task_name}.py"
    msg_literal = json.dumps(message)  

    if os_name == "windows":
        notify_block = f"""
message = {msg_literal}
notified = False

try:
    from plyer import notification
    notification.notify(title="J.A.R.V.I.S Reminder", message=message, timeout=15)
    notified = True
except Exception:
    pass

if not notified:
    try:
        from win10toast import ToastNotifier
        ToastNotifier().show_toast("J.A.R.V.I.S Reminder", message, duration=15, threaded=False)
        notified = True
    except Exception:
        pass

if not notified:
    try:
        import subprocess
        subprocess.run(["msg", "*", "/TIME:30", message], check=False)
    except Exception:
        pass

try:
    import winsound
    for freq in [800, 1000, 1200]:
        winsound.Beep(freq, 180)
        import time; time.sleep(0.08)
except Exception:
    pass
"""

    elif os_name == "mac":
        notify_block = f"""
message = {msg_literal}
notified = False

try:
    from plyer import notification
    notification.notify(title="J.A.R.V.I.S Reminder", message=message, timeout=15)
    notified = True
except Exception:
    pass

if not notified:
    try:
        import subprocess
        script = 'display notification "{{}}" with title "J.A.R.V.I.S Reminder"'.format(
            message.replace('"', '')
        )
        subprocess.run(["osascript", "-e", script], check=False)
    except Exception:
        pass
"""

    else:  # linux
        notify_block = f"""
message = {msg_literal}
notified = False

try:
    from plyer import notification
    notification.notify(title="J.A.R.V.I.S Reminder", message=message, timeout=15)
    notified = True
except Exception:
    pass

if not notified:
    try:
        import subprocess
        subprocess.run(
            ["notify-send", "--urgency=normal", "--expire-time=15000",
             "J.A.R.V.I.S Reminder", message],
            check=False
        )
    except Exception:
        pass
"""

    script_body = f"""# Auto-generated by J.A.R.V.I.S reminder — do not edit
import sys, os, pathlib
{notify_block}
# Self-delete after firing
try:
    pathlib.Path(__file__).unlink(missing_ok=True)
except Exception:
    pass
"""
    script_path.write_text(script_body, encoding="utf-8")
    script_path.chmod(0o600)   # owner read/write only
    return script_path

def _schedule_windows(target_dt: datetime, task_name: str,
                      script_path: Path, message: str) -> str:
    python_exe = Path(sys.executable)
    pythonw = python_exe.parent / "pythonw.exe"
    if pythonw.exists():
        python_exe = pythonw

    xml_path = _scripts_dir() / f"{task_name}.xml"
    xml_content = (
        '<?xml version="1.0" encoding="UTF-16"?>\n'
        '<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\n'
        '  <RegistrationInfo><Description>J.A.R.V.I.S Reminder</Description></RegistrationInfo>\n'
        '  <Triggers><TimeTrigger>\n'
        f'    <StartBoundary>{target_dt.strftime("%Y-%m-%dT%H:%M:%S")}</StartBoundary>\n'
        '    <Enabled>true</Enabled>\n'
        '  </TimeTrigger></Triggers>\n'
        '  <Actions><Exec>\n'
        f'    <Command>{python_exe}</Command>\n'
        f'    <Arguments>"{script_path}"</Arguments>\n'
        '  </Exec></Actions>\n'
        '  <Settings>\n'
        '    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n'
        '    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n'
        '    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n'
        '    <StartWhenAvailable>true</StartWhenAvailable>\n'
        '    <ExecutionTimeLimit>PT5M</ExecutionTimeLimit>\n'
        '    <Enabled>true</Enabled>\n'
        '  </Settings>\n'
        '  <Principals><Principal>\n'
        '    <LogonType>InteractiveToken</LogonType>\n'
        '    <RunLevel>LeastPrivilege</RunLevel>\n'
        '  </Principal></Principals>\n'
        '</Task>'
    )

    xml_path.write_text(xml_content, encoding="utf-16")

    result = subprocess.run(
        ["schtasks", "/Create", "/TN", task_name, "/XML", str(xml_path), "/F"],
        capture_output=True, text=True, **_CNW,
    )

    try:
        xml_path.unlink(missing_ok=True)
    except Exception:
        pass

    if result.returncode != 0:
        script_path.unlink(missing_ok=True)
        err = (result.stderr or result.stdout).strip()
        print(f"[Reminder] ❌ schtasks: {err}")
        return ""  

    return task_name


def _schedule_mac(target_dt: datetime, task_name: str,
                  script_path: Path) -> str:
    agents_dir = Path.home() / "Library" / "LaunchAgents"
    agents_dir.mkdir(parents=True, exist_ok=True)

    label     = f"com.jarvis.reminder.{task_name}"
    plist_path = agents_dir / f"{label}.plist"

    plist_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>             <string>{label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>{sys.executable}</string>
    <string>{script_path}</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Year</key>   <integer>{target_dt.year}</integer>
    <key>Month</key>  <integer>{target_dt.month}</integer>
    <key>Day</key>    <integer>{target_dt.day}</integer>
    <key>Hour</key>   <integer>{target_dt.hour}</integer>
    <key>Minute</key> <integer>{target_dt.minute}</integer>
  </dict>
  <key>RunAtLoad</key>         <false/>
  <key>StandardOutPath</key>   <string>/dev/null</string>
  <key>StandardErrorPath</key> <string>/dev/null</string>
</dict>
</plist>
"""
    plist_path.write_text(plist_content, encoding="utf-8")
    plist_path.chmod(0o644)

    result = subprocess.run(
        ["launchctl", "load", str(plist_path)],
        capture_output=True, text=True,
    )

    if result.returncode != 0:
        plist_path.unlink(missing_ok=True)
        script_path.unlink(missing_ok=True)
        print(f"[Reminder] ❌ launchctl: {result.stderr.strip()}")
        return ""

    return label


def _schedule_linux(target_dt: datetime, task_name: str,
                    script_path: Path) -> str:

    if shutil.which("systemd-run"):
        on_calendar = target_dt.strftime("%Y-%m-%d %H:%M:00")
        result = subprocess.run(
            [
                "systemd-run",
                "--user",
                f"--on-calendar={on_calendar}",
                f"--unit={task_name}",
                "--",
                sys.executable, str(script_path),
            ],
            capture_output=True, text=True,
        )
        if result.returncode == 0:
            return task_name
        print(f"[Reminder] ⚠️ systemd-run failed: {result.stderr.strip()}, trying 'at'")

    if shutil.which("at"):
        at_time = target_dt.strftime("%H:%M %Y-%m-%d")
        cmd_str = f"{sys.executable} {script_path}\n"
        result  = subprocess.run(
            ["at", at_time],
            input=cmd_str, capture_output=True, text=True,
        )
        if result.returncode == 0:
            return task_name
        print(f"[Reminder] ❌ at: {result.stderr.strip()}")
        return ""

    print("[Reminder] ❌ Neither systemd-run nor at found on this Linux system.")
    return ""


def _parse_target_datetime(date_str: str, time_str: str, message: str) -> tuple[datetime | None, str]:
    """Parse relative time, natural date/time, or standard YYYY-MM-DD HH:MM into a datetime object."""
    now = datetime.now()
    raw_time = time_str.strip().lower()
    raw_date = date_str.strip().lower()
    raw_msg  = message.strip().lower()
    combined = f"{raw_time} {raw_msg} {raw_date}"

    # 1. Relative durations: e.g. "5 min", "5 minutes", "10 min ka", "1 hr", "2 ghante", "30 sec"
    m_rel = re.search(r"(\d+)\s*(?:minutes?|mins?|min|m|ghante?|hours?|hrs?|hr|h|seconds?|secs?|sec|s)\b", combined)
    if m_rel:
        val = int(m_rel.group(1))
        unit = m_rel.group(0).lower()
        if any(h in unit for h in ["h", "ghant"]):
            return now + timedelta(hours=val), f"{val} hour(s)"
        elif any(s in unit for s in ["s"]) and not any(m in unit for m in ["min", "m"]):
            return now + timedelta(seconds=max(val, 10)), f"{val} second(s)"
        else:
            return now + timedelta(minutes=val), f"{val} minute(s)"

    # 2. Base date resolution: "kal" / "tomorrow" -> today + 1 day
    base_date = now.date()
    if any(k in f"{raw_date} {raw_msg}" for k in ["kal", "tomorrow"]):
        base_date = base_date + timedelta(days=1)
    elif any(k in f"{raw_date} {raw_msg}" for k in ["parso"]):
        base_date = base_date + timedelta(days=2)
    elif raw_date:
        for fmt in ("%Y-%m-%d", "%d-%m-%Y", "%d/%m/%Y", "%Y/%m/%d", "%d.%m.%Y"):
            try:
                base_date = datetime.strptime(raw_date, fmt).date()
                break
            except ValueError:
                pass

    # 3. Direct standard time parsing (e.g. 18:30, 6:30 pm)
    clean_t = re.sub(r"\b(baje|o'?clock|subah|shaam|dopahar|raat)\b", "", raw_time).strip()
    for fmt in ("%H:%M", "%I:%M %p", "%I %p", "%I:%M%p", "%I%p", "%H"):
        try:
            parsed_t = datetime.strptime(clean_t, fmt).time()
            target_dt = datetime.combine(base_date, parsed_t)
            if target_dt <= now and not any(k in f"{raw_date} {raw_msg}" for k in ["kal", "tomorrow", "parso"]):
                target_dt += timedelta(days=1)
            return target_dt, ""
        except ValueError:
            pass

    # 4. Regex search for time in combined string (e.g. "6:30 pm", "6 pm", "6 baje", "18:00")
    m_time = re.search(r"\b(\d{1,2})(?::(\d{2}))?\s*(am|pm|baje)?\b", combined)
    if m_time:
        hh = int(m_time.group(1))
        mm = int(m_time.group(2)) if m_time.group(2) else 0
        suffix = m_time.group(3) or ""
        if "shaam" in combined or "raat" in combined:
            if hh < 12:
                hh += 12
        elif suffix == "pm" and hh < 12:
            hh += 12
        elif suffix == "am" and hh == 12:
            hh = 0
        try:
            parsed_t = dt_time(hour=hh, minute=mm)
            target_dt = datetime.combine(base_date, parsed_t)
            if target_dt <= now and not any(k in f"{raw_date} {raw_msg}" for k in ["kal", "tomorrow", "parso"]):
                target_dt += timedelta(days=1)
            return target_dt, ""
        except ValueError:
            pass

    return None, ""


def reminder(
    parameters: dict,
    response=None,
    player=None,
    session_memory=None,
) -> str:
    params = parameters or {}
    date_str = str(params.get("date") or "").strip()
    time_str = str(params.get("time") or "").strip()
    message  = str(params.get("message") or params.get("text") or params.get("task") or "Reminder").strip()

    if not time_str and not date_str and not message:
        return "Reminder ya alarm ke liye time batao (e.g., '5 min ka alarm', 'kal shaam 6 baje')."

    target_dt, desc = _parse_target_datetime(date_str, time_str, message)
    if not target_dt:
        return "Reminder ka time samajh nahi aaya. Please specify time (e.g., '5 min baad', '6:30 pm', 'kal subah 9 baje')."

    now = datetime.now()
    if target_dt <= now:
        return "Yeh time nikal chuka hai — main past ka reminder set nahi kar sakta."

    os_name    = _get_os()
    safe_msg   = _sanitise(message)
    task_name  = f"JARVISReminder_{target_dt.strftime('%Y%m%d_%H%M%S')}"

    try:
        script_path = _write_notify_script(task_name, safe_msg, os_name)
    except Exception as e:
        return f"Could not prepare the reminder script: {e}"

    job_id = ""
    try:
        if os_name == "windows":
            job_id = _schedule_windows(target_dt, task_name, script_path, safe_msg)
        elif os_name == "mac":
            job_id = _schedule_mac(target_dt, task_name, script_path)
        else:
            job_id = _schedule_linux(target_dt, task_name, script_path)
    except Exception as e:
        print(f"[Reminder] ❌ Primary scheduler exception: {e}")

    if not job_id:
        # Fallback background timer for Windows or quick alarms if schtasks fails
        delay_sec = max(1, int((target_dt - datetime.now()).total_seconds()))
        if delay_sec <= 3600 * 24:
            try:
                cmd = f"import time, subprocess; time.sleep({delay_sec}); subprocess.run([r'{sys.executable}', r'{script_path}'])"
                subprocess.Popen([sys.executable, "-c", cmd], **_CNW)
                job_id = task_name
            except Exception as fb_err:
                print(f"[Reminder] Fallback timer error: {fb_err}")

    if not job_id:
        script_path.unlink(missing_ok=True)
        # We don't return here! We want to register it with the UI TimerManager!
        print("System scheduler me reminder register nahi ho paya. Relying on UI TimerManager only.")

    # Register with live in-app TimerManager for real-time HUD countdown & voice alert
    try:
        from core.timer_manager import add_active_timer
        cat = "alarm" if any(w in safe_msg.lower() for w in ("alarm", "timer")) else "reminder"
        add_active_timer(task_name, safe_msg, target_dt, category=cat)
    except Exception as _tm_err:
        print(f"[Reminder] TimerManager register note: {_tm_err}")

    if player:
        player.write_log(f"[Reminder] ✅ {target_dt.strftime('%Y-%m-%d %H:%M')} — {safe_msg[:40]}")

    friendly_time = target_dt.strftime("%B %d at %I:%M %p")
    if desc:
        return f"✅ Reminder/Alarm set kar diya hai ({desc} baad — {friendly_time}): '{safe_msg}'"
    return f"✅ Reminder set for {friendly_time}: '{safe_msg}'"


# ── Tool declaration (auto-discovered by core/action_loader.py) ──────────────
TOOL = {
    "name": "reminder",
    "description": (
        "Sets a timed reminder, timer, or alarm using Task Scheduler or background timer. "
        "Supports relative times like '5 min', '10 minutes', '1 hour' and specific times like '6:30 pm', 'kal shaam 6 baje'."
    ),
    "parameters": {
        "type": "OBJECT",
        "properties": {
            "time": {
                "type": "STRING",
                "description": "Time or duration (e.g. '5 min', '10 minutes', '18:30', '6:30 pm', 'kal 6 baje')"
            },
            "message": {
                "type": "STRING",
                "description": "Reminder or alarm description/reason"
            },
            "date": {
                "type": "STRING",
                "description": "Optional date (YYYY-MM-DD or 'today'/'tomorrow'). Defaults to today."
            }
        },
        "required": [
            "time"
        ]
    },
    "handler": reminder,
}
